import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
products=pd.read_csv("cleaned_products.csv")
customers=pd.read_csv("cleaned_customers.csv")
orders=pd.read_csv("cleaned_orders.csv")
order_items=pd.read_csv("cleaned_order_items.csv")
customer_feedback=pd.read_csv("cleaned_customer_feedback.csv")
delivery=pd.read_csv("cleaned_delivery_performance.csv")
merged=pd.merge(products,order_items,on="product_id")
merged=pd.merge(merged,orders,on="order_id")
merged=pd.merge(merged,customers,on="customer_id")
merged=pd.merge(merged,customer_feedback,on=["customer_id","order_id"])
merged["revenue"]=merged["quantity"]*merged["unit_price"]

# Visualization
# 1)Bar chart – Revenue by Category
revenue_by_category=merged.groupby("category")["revenue"].sum().sort_values()
revenue_by_category.plot(kind="bar",fontsize=8,edgecolor="black")
plt.title("Revenue by Category")
plt.xlabel("Category")
plt.xticks(rotation=0)
plt.tight_layout()
plt.ylabel("Revenue in Rupees(₹)")
plt.show()
# 2)Bar chart – Top 10 Selling Products (Quantity)
top10_selling=merged.groupby("product_name")["quantity"].sum().sort_values(ascending=False).head(10)
top10_selling.plot(kind="bar")
plt.title("Top 10 Selling Products")
plt.xlabel("Product")
plt.xticks(fontsize=8,rotation=0)
plt.tight_layout()
plt.ylabel("Quantity sold")
plt.show()
# 3)Bar chart – Top 10 Customers by Spending
top10_customer_by_spending=merged.groupby("customer_name")["order_total"].sum().sort_values(ascending=False).head(10)
top10_customer_by_spending.plot(kind="bar",color="orange")
plt.title("Top 10 Customers by Spending in(₹)")
plt.xlabel("customer")
plt.xticks(fontsize=8,rotation=0)
plt.tight_layout()
plt.ylabel("Spending")
plt.show()
# 4)Bar chart – Orders by Customer Segment
order_by_segment=merged.groupby("customer_segment")["order_id"].nunique()
order_by_segment.plot(kind="bar",color="orange",edgecolor="black")
plt.title("Orders by Customer Segment")
plt.xlabel("customer segment")
plt.xticks(fontsize=8,rotation=0)
plt.tight_layout()
plt.ylabel("Number of order")
plt.show()
# 5)Pie chart – Payment Method Distribution
payment_method_distrubution=merged["payment_method"].value_counts()
payment_method_distrubution.plot(kind="pie",autopct="%1.1f%%",startangle=90)
plt.title("Payment Method Distribution")
plt.ylabel("")
plt.show()
# 6)Pie chart – Delivery Status Distribution
delivery_status_distrubution=merged["delivery_status"].value_counts()
delivery_status_distrubution.plot(kind="pie",autopct="%1.1f%%",startangle=90)
plt.title("Delivery status Distribution")
plt.ylabel("")
plt.show()
# 7)Histogram – Product Price Distribution
plt.hist(merged["price"],bins=10,edgecolor="black")
plt.title("Product Price Distribution")
plt.xlabel("Price in(₹)")
plt.ylabel("Number of Products")
plt.show()
# 8)Histogram – Customer Ratings
plt.hist(merged["rating"],bins=5,edgecolor="black")
plt.title("Customer Ratings")
plt.xlabel("Rating")
plt.ylabel("Number of Customer")
plt.show()
# Kdeplot– Customer Ratings
sns.kdeplot(merged["rating"])
plt.title("Customer Ratings")
plt.show()
# 9)Box Plot – Product Price by Category
sns.boxplot(x="category",y="price",data=merged)
plt.title("Product Price by Category")
plt.xlabel("Category")
plt.xticks(rotation=45,fontsize=8)
plt.ylabel("Price")
plt.show()
# 10)Count Plot – Customer Segments
sns.countplot(x="customer_segment",data=merged)
plt.show()
# 11)Line Chart – Monthly Revenue Trend
monthly_revenue=merged.groupby("month")["revenue"].sum()
monthly_revenue.index=["january","Febuary","March","April","May","June","July","August","September","October","November","December"]
monthly_revenue.plot(kind="line",marker="o")
plt.title("Monthly Revenue Trend")
plt.xlabel("Month")
plt.xticks(range(12),monthly_revenue.index)
plt.ylabel("revenue(₹)")
plt.show()
# 12)Line Chart – Daily Order Trend(1 month)
merged["order_date"]=pd.to_datetime(merged["order_date"],errors="coerce")
merged["date"]=merged["order_date"].dt.date
daily_trend=merged.groupby("date")["order_id"].nunique().sort_index().head(30)
plt.figure(figsize=(12,5))
daily_trend.plot(kind="line",marker="o",markersize=3)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
# 13)Line Chart – Monthly Order Trend
monthly_order=merged.groupby("month")["order_id"].nunique()
monthly_order.index=["january","Febuary","March","April","May","June","July","August","September","October","November","December"]
monthly_order.plot(kind="line",marker="o",linestyle="--",markerfacecolor="black")
plt.title(" Monthly Order Trend")
plt.xlabel("Month")
plt.xticks(range(12),monthly_order.index)
plt.ylabel("Order")
plt.show()
# 14)Line Chart – Average Customer Rating by Month
avg_cust_rating=merged.groupby("month")["rating"].mean()
avg_cust_rating.index=["january","Febuary","March","April","May","June","July","August","September","October","November","December"]
avg_cust_rating.plot(kind="line",marker="o",linestyle="--",markerfacecolor="black")
plt.title(" Monthly Average Rating")
plt.xlabel("Month")
plt.xticks(range(12),avg_cust_rating.index)
plt.ylabel("Average rating")
plt.show()
# 15)Bar Chart – Revenue by Payment Method
rev_method=merged.groupby("payment_method")["revenue"].sum()/1000000
rev_method.plot(kind="bar")
plt.title("Revenue by Payment Method")
plt.xlabel("Payment Method")
plt.ylabel("Revenue in millions(₹)")
plt.show()
# 16)Bar Chart –Bar Chart – Average Revenue by Customer Segment
cust_ang_revenue=merged.groupby("customer_segment")["revenue"].mean()
cust_ang_revenue.plot(kind="bar",edgecolor="black")
plt.title("Average Revenue by Customer Segment")
plt.xlabel("Customer segment")
plt.xticks(rotation=0)
plt.ylabel("Average revenue")
plt.show()
# 17)Bar Chart – Top Delivery Partners by Orders
top_delvery_partner=merged.groupby("delivery_partner_id")["order_id"].nunique().head(10)
print(top_delvery_partner)
top_delvery_partner.plot(kind="bar",edgecolor="black")
plt.title("Top Delivery Partners by Orders")
plt.xlabel("Delivery partner id")
plt.xticks(rotation=0)
plt.ylabel("Orders delivered")
plt.show()#here each delivery partner has only delivered 1 order
# 18)Scatter Plot – Scatter Plot – Price vs Revenue
plt.scatter(merged["unit_price"],merged["revenue"])
plt.title("Plot – Price vs Revenue")
plt.xlabel("Price")
plt.ylabel("revenue")
plt.show()
# 19)Scatter Plot – Margin % vs Revenue
plt.scatter(merged["margin_percentage"],merged["revenue"])
plt.title(" Margin % vs Revenue")
plt.xlabel(" Margin % ")
plt.ylabel("Revenue")
plt.show()
# 20)Scatter Plot – Quantity vs Revenue
plt.scatter(merged["quantity"],merged["revenue"])
plt.title(" Quantity vs Revenue")
plt.xlabel(" Quantity ")
plt.ylabel("Revenue")
plt.show()
# 21)Scatter Plot – Product Price vs Rating
plt.scatter(merged["price"],merged["rating"])
plt.title("Product Price vs Rating")
plt.xlabel(" Product price")
plt.ylabel("Rating")
plt.show()
# 23)Heatmap – Correlation of important Numerical Columns
corr1=merged[["price","unit_price","quantity","revenue","rating","margin_percentage","order_total"]]
sns.heatmap(corr1.corr(),annot=True)
plt.show()
print(merged.info())
# 24)Heatmap – Monthly Revenue Pivot Table
monthly_pivot=merged.pivot_table(values="revenue",index="month",aggfunc="sum")
monthly_pivot.index=["january","Febuary","March","April","May","June","July","August","September","October","November","December"]
sns.heatmap(monthly_pivot,annot=True,fmt=".0f")
plt.show()
# 25)Stacked Bar Chart – Revenue by Category and Payment Method
stacked_bar_revenue=merged.pivot_table(values="revenue",index="category",columns="payment_method",aggfunc="sum")
stacked_bar_revenue.plot(kind="bar",stacked=True,figsize=(12,8))
plt.title(" Revenue by Category and Payment Method")
plt.xlabel("Category")
plt.xticks(rotation=45,fontsize=8)
plt.ylabel("Revenue")
plt.show()
# 26)Stacked Bar Chart – Orders by Month and Delivery Status
stacked_bar_order=merged.pivot_table(columns="month",index="delivery_status",values="order_id",aggfunc="nunique")
stacked_bar_order.plot(kind="bar",stacked=True,figsize=(12,8))
plt.title("Orders by Month and Delivery Status")
plt.xlabel("Delivery Status")
plt.xticks(rotation=0)
plt.ylabel("Number of order")
plt.legend(title="Month")
plt.show()
# 27)Grouped Bar Chart – Revenue vs Quantity by Category
grouped_bar_chart=merged.groupby("category")[["revenue","quantity"]].sum()
grouped_bar_chart.plot(kind="bar")
plt.title()
plt.show()
# 28)Pair Plot – Numerical Features (price, quantity, revenue, rating, margin_percentage)
sns.pairplot(merged[["price","quantity","revenue","rating","margin_percentage"]])
plt.show()
# 29)Violin Plot – Ratings by Category
sns.violinplot(data=merged,x="category",y="rating")
plt.title("Ratings by Category")
plt.xlabel("Category")
plt.ylabel("Rating")
plt.tight_layout()
plt.xticks(fontsize=8,rotation=0)
plt.show()