import pandas as pd
products=pd.read_csv("cleaned_products.csv")
customers=pd.read_csv("cleaned_customers.csv")
orders=pd.read_csv("cleaned_orders.csv")
order_items=pd.read_csv("cleaned_order_items.csv")
customer_feedback=pd.read_csv("cleaned_customer_feedback.csv")
delivery=pd.read_csv("cleaned_delivery_performance.csv")
merged=pd.merge(products,order_items,on="product_id")
merged=pd.merge(merged,orders,on="order_id")
merged=pd.merge(merged,customers,on="customer_id")
merged=pd.merge(merged,customer_feedback,on=["customer_id","order_id"])#on=2 col named because both contein two same columns
print(merged.isnull().sum())#no null value detected
# 1)Top selling products
Top10_selling_product=merged.groupby("product_name")["quantity"].sum().sort_values(ascending=False).head(10)
print("The top selling products are:\n",Top10_selling_product)
# 2)Revenue by category
merged["revenue"]=merged["unit_price"]*merged["quantity"]
rev_by_category=merged.groupby("category")["revenue"].sum()
print("Total revenues as per categories(in rupees):\n",rev_by_category,)
# 3)Average customer rating by product category
avg_cust_rating=merged.groupby("category")["rating"].mean()
print("The average customer rating as per category:\n",avg_cust_rating)
# 4)Find total revenue generated by each customer
avg_revenue_by_customer=merged.groupby("customer_id")["revenue"].sum().sort_values(ascending=False)
print(avg_revenue_by_customer)
# 5)Top 10 customers by total spending
top_10_cust_by_spending=merged.groupby(["customer_id","customer_name"])["order_total"].sum().sort_values(ascending=False).head(10).reset_index(name="Total spending")
print(top_10_cust_by_spending)
# 6)payment method revenue distribution
payment_method_revenue=merged.groupby("payment_method")["revenue"].sum().sort_values().reset_index(name="revenue")
print("payment method revenue distribution",payment_method_revenue)
# 7)Find the number of orders placed by each customer segment
order_per_cust_segment=merged.groupby("customer_segment")["order_id"].nunique()
print(order_per_cust_segment)
# 8)Find average order value for each customer segment
avg_order_val_cust_segment=merged.groupby("customer_segment")["order_total"].mean().reset_index(name="average order value")
print(" average order value for each customer segment:\n",avg_order_val_cust_segment)
#A 9)Find the top-selling product in each category
top_selling_category=merged.groupby(["category","product_name"])["quantity"].sum().reset_index()
top_selling_category=top_selling_category.loc[top_selling_category.groupby("category")["quantity"].idxmax()]#without reset_index() category and produce name become index
print("the top-selling product in each category:\n",top_selling_category)
# 10)Find the highest revenue-generating product in each category
highest_revenue_by_product_in_category=merged.groupby(["category","product_name"])["revenue"].sum().reset_index()
highest_revenue_by_product_in_category=highest_revenue_by_product_in_category.loc[highest_revenue_by_product_in_category.groupby("category")["revenue"].idxmax()]
print("The highest revenue generated by product in each category:\n",highest_revenue_by_product_in_category)
# 11)Find customers who have placed more than 5 orders.
customers_with_5order=merged.groupby(["customer_id","customer_name"])["order_id"].nunique().sort_values(ascending=False)
customers_with_5order=customers_with_5order[customers_with_5order>5]
print(customers_with_5order)
# 12)Find products that have never been ordered
unsold_products=merged.groupby(["product_id","product_name"])["quantity"].count()
unsold_products=unsold_products[unsold_products==0]
print(unsold_products)
# 13)Find customers who purchased products from more than one category.
more_than_one_category=merged.groupby(["customer_id","customer_name"])["category"].nunique().reset_index(name="total_categories")
more_than_one_category=more_than_one_category[more_than_one_category["total_categories"]>1]
print(more_than_one_category)
# 14)Find average quantity purchased per order
Average_quantity_per_order=merged['quantity'].mean()
print("Averege quantity purchased per order:",Average_quantity_per_order)
# 15)Find monthly revenue trend
month_revenue=merged.groupby("month")["revenue"].sum().sort_values(ascending=False).reset_index(name="Total Revenue")
print(month_revenue)
# 16)Find daily order trend
merged["order_date"]=pd.to_datetime(merged["order_date"],errors="coerce")
merged["date"]=merged["order_date"].dt.date
daily_order_trend=merged.groupby("date")["order_id"].nunique()
print(daily_order_trend)
